title: James McElwee
description: Systems Engineer
site_title: 'James McElwee'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: j-mcelwee
blog_url: https://j-mcelwee.github.io
email: jamesemcelwee@outlook.com
linkedin_url: https://www.linkedin.com/in/james-mcelwee-a4811b153
keybase_username: delete
twitter_username: delete
reddit_username: delete

# absolute or relative
profile_picture: assets/images/Headshot.jpg

# Google Analytics ID
google_analytics: 